Updated azure-pipelines-1.yml

diff --git a/azure-pipelines-1.yml b/azure-pipelines-1.yml
--- a/azure-pipelines-1.yml
+++ b/azure-pipelines-1.yml
@@ -12,18 +12,32 @@ pool:
 steps:
 
 - script: |
-    CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
-    CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
-
-    CHROMEDRIVER_URL="https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
-    wget $CHROMEDRIVER_URL -O chromedriver_linux64.zip
-    unzip chromedriver_linux64.zip
-
-    sudo mv chromedriver /usr/local/bin/
-    sudo chmod +x /usr/local/bin/chromedriver
-
-    echo "Versión de Google Chrome instalada: $CHROME_VERSION"
-
-    CHROMEDRIVER_INSTALLED_VERSION=$(chromedriver --version)
-    echo "Versión de ChromeDriver instalada: $CHROMEDRIVER_INSTALLED_VERSION"
-  displayName: 'Instalar ChromeDriver compatible con la versión de Google Chrome'
+    sleep 2m
+  displayName: '2 minutes'
+  timeoutInMinutes: 1
+  continueOnError: true
+  # retryCountOnTaskFailure: 3
+- script: echo Hello, world!
+  displayName: 'Run a one-line script'
+- task: Bash@3
+  displayName: Test on the Android Emulator
+  inputs:
+    targetType: inline
+    script: |
+      #!/bin/bash
+      timeout 300s bash -c '
+        echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "system-images;android-28;google_apis_playstore;x86"
+        $ANDROID_HOME/platform-tools/adb devices
+        echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n test_android_emulator -k "system-images;android-28;google_apis_playstore;x86" --force
+        nohup $ANDROID_HOME/emulator/emulator -avd test_android_emulator -no-snapshot > /dev/null 2>&1 &
+        $ANDROID_HOME/platform-tools/adb wait-for-device shell "while [[ -z \$(getprop sys.boot_completed | tr -d '\\r') ]]; do sleep 1; done; input keyevent 82"
+        echo "Emulator started"
+      '
+      if [ $? -eq 0 ]; then
+        echo "El script se completó dentro del límite de tiempo."
+      else
+        echo "El script superó el límite de tiempo de 5 minutos y se detuvo."
+      fi
+  retryCountOnTaskFailure: 3
+- script: echo Hello, world!
+  displayName: 'Run a one-line script'
